In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Training_Scores.csv")
df

,Total sentences,Total words,Total Syllable,Gunning Fog Index,Flesch Reading Ease,Flesch-Kincaid Grade,classification
0,1322,5850,NaN,9.76,59.85,6.01,0
1,1239,5499,NaN,8.63,66.35,5.11,0
2,1267,4155,NaN,10.24,54.20,6.51,0
3,1793,6392,NaN,9.47,56.05,6.33,0
4,1395,4555,NaN,9.39,55.94,6.27,0
...,...,...,...,...,...,...,...
59,968,2957,NaN,11.22,49.47,7.12,1
60,1023,3119,NaN,11.18,50.90,6.92,1
61,1853,6477,NaN,12.41,42.52,8.20,1
62,1150,3249,NaN,11.10,49.56,7.05,1
63,1113,3612,NaN,12.31,43.29,8.03,1

In [3]:
df = df.drop(columns=(["Total sentences", "Total words", "Total Syllable"]), axis = 1)
df

,Gunning Fog Index,Flesch Reading Ease,Flesch-Kincaid Grade,classification
0,9.76,59.85,6.01,0
1,8.63,66.35,5.11,0
2,10.24,54.20,6.51,0
3,9.47,56.05,6.33,0
4,9.39,55.94,6.27,0
...,...,...,...,...
59,11.22,49.47,7.12,1
60,11.18,50.90,6.92,1
61,12.41,42.52,8.20,1
62,11.10,49.56,7.05,1
63,12.31,43.29,8.03,1

In [4]:
X = df.drop(columns=(["classification"]), axis = 1)
X

    Gunning Fog Index  Flesch Reading Ease  Flesch-Kincaid Grade
0                9.76                59.85                  6.01
1                8.63                66.35                  5.11
2               10.24                54.20                  6.51
3                9.47                56.05                  6.33
4                9.39                55.94                  6.27
..                ...                  ...                   ...
59              11.22                49.47                  7.12
60              11.18                50.90                  6.92
61              12.41                42.52                  8.20
62              11.10                49.56                  7.05
63              12.31                43.29                  8.03

[64 rows x 3 columns]

In [5]:
y = df["classification"]

In [6]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.091, random_state = 21)

In [9]:
X_train

    Gunning Fog Index  Flesch Reading Ease  Flesch-Kincaid Grade
31              10.22                56.42                  6.41
7                9.45                59.51                  5.78
28              10.49                51.95                  6.83
53              11.19                49.14                  7.41
21              12.00                43.96                  8.16
24               9.86                57.15                  6.05
26              10.35                55.33                  6.52
32               8.08                69.94                  4.60
14              10.54                52.26                  6.72
30               9.28                63.02                  5.61
60              11.18                50.90                  6.92
3                9.47                56.05                  6.33
11               9.38                59.77                  5.84
25              10.34                53.96                  6.52
57              11.91                48.80                  7.10
0                9.76                59.85                  6.01
13              10.54                56.11                  6.39
29              11.02                50.71                  7.01
63              12.31                43.29                  8.03
43               9.46                57.71                  6.07
47              11.43                46.91                  7.49
62              11.10                49.56                  7.05
39              10.67                54.35                  6.52
33              10.22                55.28                  6.43
42               9.78                57.69                  6.15
1                8.63                66.35                  5.11
27              11.00                50.56                  6.91
16               9.64                57.67                  6.11
40              10.76                53.58                  6.62
55              10.63                53.21                  6.42
6               10.49                54.01                  6.50
18              10.81                52.13                  6.85
37              10.37                53.50                  6.59
45              10.35                52.58                  6.69
5                8.97                62.01                  5.41
54               9.30                60.86                  5.67
12              10.06                60.83                  5.71
50              10.69                52.24                  6.80
20              11.00                50.32                  7.07
38              10.46                52.76                  6.75
36               9.73                57.63                  6.05
51              10.43                54.29                  6.44
58              10.60                53.58                  6.59
41               7.94                72.51                  3.95
44              10.94                51.96                  6.71
46              10.19                53.30                  6.63
8               10.74                52.49                  6.60
10              10.48                51.89                  6.83
49              11.59                46.73                  7.54
34              11.16                48.99                  7.32
35              10.88                51.62                  6.93
61              12.41                42.52                  8.20
59              11.22                49.47                  7.12
48              11.59                48.30                  7.36
4                9.39                55.94                  6.27
56              10.33                52.05                  6.93
15               8.62                64.86                  4.90
9                8.60                66.71                  4.73

In [10]:
X_test

    Gunning Fog Index  Flesch Reading Ease  Flesch-Kincaid Grade
23               7.45                74.63                  3.39
52              11.25                48.51                  7.32
17              10.72                50.93                  6.93
22               8.59                65.23                  4.84
2               10.24                54.20                  6.51
19              10.43                54.04                  6.74

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
scaler = StandardScaler()

In [14]:
X_train_scaled = scaler.fit_transform(X_train)

In [15]:
X_test_scaled = scaler.transform(X_test)

In [29]:
X_train_scaled

array([[-0.12975584,  0.30064738, -0.09479154],
       [-0.9268529 ,  0.81239612, -0.86793507],
       [ 0.14974573, -0.43964933,  0.42063748],
       [ 0.87437943, -0.90502601,  1.13242041],
       [ 1.71288414, -1.762909  ,  2.05282937],
       [-0.5024246 ,  0.42154595, -0.53658785],
       [ 0.00481899,  0.1201276 ,  0.04020177],
       [-2.34506457,  2.53975511, -2.31604518],
       [ 0.20150528, -0.38830884,  0.28564416],
       [-1.10283537,  1.39370293, -1.07656111],
       [ 0.86402752, -0.61354453,  0.53108655],
       [-0.90614908,  0.23937003, -0.1929685 ],
       [-0.99931627,  0.85545588, -0.79430236],
       [-0.00553292, -0.10676423,  0.04020177],
       [ 1.61971695, -0.96133493,  0.7519847 ],
       [-0.6059437 ,  0.86870504, -0.58567633],
       [ 0.20150528,  0.2493069 , -0.11933578],
       [ 0.69839696, -0.64501128,  0.64153563],
       [ 2.03379335, -1.8738707 ,  1.89329182],
       [-0.91650099,  0.51429006, -0.51204361],
       [ 1.12282527, -1.27434629,  1.23059737],
       [ 0.78121224, -0.83546793,  0.69062411],
       [ 0.33608011, -0.04217458,  0.04020177],
       [-0.12975584,  0.11184688, -0.0702473 ],
       [-0.58523988,  0.51097777, -0.41386665],
       [-1.77570952,  1.94519914, -1.69016708],
       [ 0.67769314, -0.66985345,  0.51881443],
       [-0.73016661,  0.50766548, -0.46295513],
       [ 0.4292473 , -0.16969773,  0.16292297],
       [ 0.29467247, -0.23097509, -0.08251942],
       [ 0.14974573, -0.09848351,  0.01565753],
       [ 0.48100685, -0.40983872,  0.44518172],
       [ 0.02552281, -0.18294689,  0.12610661],
       [ 0.00481899, -0.33531221,  0.2488278 ],
       [-1.42374458,  1.22643231, -1.3220035 ],
       [-1.08213155,  1.03597566, -1.00292839],
       [-0.2953864 ,  1.03100723, -0.95383991],
       [ 0.35678393, -0.39162113,  0.38382112],
       [ 0.67769314, -0.70960092,  0.71516835],
       [ 0.11869   , -0.3055016 ,  0.32246052],
       [-0.63699943,  0.5010409 , -0.53658785],
       [ 0.08763427, -0.05211145, -0.05797519],
       [ 0.26361674, -0.16969773,  0.12610661],
       [-2.48999131,  2.96538432, -3.11373295],
       [ 0.61558168, -0.43799318,  0.27337204],
       [-0.16081157, -0.21606978,  0.17519509],
       [ 0.40854348, -0.35021751,  0.13837873],
       [ 0.13939382, -0.4495862 ,  0.42063748],
       [ 1.28845583, -1.3041569 ,  1.29195796],
       [ 0.8433237 , -0.92986818,  1.02197133],
       [ 0.55347022, -0.4943021 ,  0.54335867],
       [ 2.13731244, -2.00139384,  2.10191785],
       [ 0.90543516, -0.85037323,  0.77652894],
       [ 1.28845583, -1.04414217,  1.07105981],
       [-0.98896436,  0.22115244, -0.26660122],
       [-0.01588483, -0.42308788,  0.54335867],
       [-1.78606143,  1.69843357, -1.94788159],
       [-1.80676525,  2.00482035, -2.15650763]])

In [30]:
from sklearn.linear_model import LogisticRegression

In [31]:
log_reg = LogisticRegression(random_state = 0).fit(X_train_scaled, y_train)

In [32]:
log_reg.predict(X_train_scaled)

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0], dtype=int64)

In [33]:
log_reg.score(X_train_scaled, y_train)

0.7586206896551724

In [34]:
log_reg.score(X_test_scaled, y_test)

0.5

In [49]:
log_reg1 = LogisticRegression(random_state = 0, C = 0.01, fit_intercept = True, penalty = 'l2').fit(X_train_scaled, y_train)

In [50]:
log_reg1.score(X_train_scaled, y_train)

0.7758620689655172

In [51]:
log_reg.score(X_test_scaled, y_test)

0.5